version: '3.4'

services:
  youtube-dl:
    image: agrippa1994/youtube-dl-ui
    build:
      context: .
      target: build_youtube_dl
    command: ["node", "dist/apps/api/main.js"]
    networks:
      - http
    volumes:
      - downloads:/usr/share/app/downloads

networks:
  http:
    external:
      name: main

volumes:
  downloads:
