version: '3.4'

services:
  api:
    build:
      context: .
      target: build_api
    command: ["node", "dist/apps/api/main.js"]
    networks:
      - internal
    volumes:
      - downloads:/usr/share/app/downloads

  youtube-dl:
    build:
      context: .
      target: build_youtube_dl
    networks:
      - internal
      - http
    volumes:
      - ./config/nginx/youtube_dl.conf:/etc/nginx/conf.d/default.conf:ro


networks:
  http:
    external:
      name: main
  internal:

volumes:
  downloads:
