name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Docker Registry
      run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.PASSWORD }}
    - name: Build the Docker image
      run: |
        docker-compose build
        docker-compose push
    
